/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class FrmCuaca extends javax.swing.JFrame {

    /** Creates new form FrmCuaca */
   public Connection con;
   static String a,b,c;
    public FrmCuaca() {
        initComponents();
       
        
        lblHari.setText("");
        lblMonitoring.setText("");
        lblMax.setText("");
        lblMin.setText("");
        lblAngin.setText("");
        lblLembab.setText("");
        lblTekanan.setText("");
        lblSuhu.setText(""); 
        
        
    }

    public FrmCuaca (Connection con){
        initComponents();
        
        lblHari.setText("");
        lblMonitoring.setText("");
        lblMax.setText("");
        lblMin.setText("");
        lblAngin.setText("");
        lblLembab.setText("");
        lblTekanan.setText("");
        lblSuhu.setText(""); 
        
        this.con = con;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMonitoring = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblAngin = new javax.swing.JLabel();
        lblLembab = new javax.swing.JLabel();
        lblTekanan = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblGambar = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        cmdTampil = new javax.swing.JButton();
        dcsTanggal = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuInput = new javax.swing.JMenu();
        mbExit = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(579, 431));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 38, 49, 26));

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 44, 182, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 0), new java.awt.Color(255, 204, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        lblMonitoring.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMonitoring.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMonitoring.setText("Monitoring Cuaca");
        jPanel1.add(lblMonitoring);
        lblMonitoring.setBounds(130, 13, 229, 49);

        lblHari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHari.setText("a");
        jPanel1.add(lblHari);
        lblHari.setBounds(185, 68, 118, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Suhu Maksimum");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(263, 97, 100, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Suhu Minimum");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(263, 123, 91, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kecepatan Angin");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(263, 157, 104, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Kelembapan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(263, 183, 74, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tekanan Udara");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(263, 209, 90, 15);

        lblMax.setText("a");
        jPanel1.add(lblMax);
        lblMax.setBounds(416, 97, 40, 14);

        lblMin.setText("b");
        jPanel1.add(lblMin);
        lblMin.setBounds(415, 123, 50, 14);

        lblAngin.setText("c");
        jPanel1.add(lblAngin);
        lblAngin.setBounds(416, 157, 50, 14);

        lblLembab.setText("d");
        jPanel1.add(lblLembab);
        lblLembab.setBounds(415, 183, 50, 14);

        lblTekanan.setText("e");
        jPanel1.add(lblTekanan);
        lblTekanan.setBounds(415, 209, 50, 14);

        lblSuhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSuhu.setText("Suhu Nya");
        jPanel1.add(lblSuhu);
        lblSuhu.setBounds(41, 97, 132, 49);

        lblGambar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/04n.png"))); // NOI18N
        lblGambar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lblGambar);
        lblGambar.setBounds(41, 157, 132, 120);

        lblStatus.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblStatus.setText("Broken Clouds");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(60, 280, 90, 15);

        cmdTampil.setText("Tampilkan");
        cmdTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTampilActionPerformed(evt);
            }
        });
        jPanel1.add(cmdTampil);
        cmdTampil.setBounds(263, 257, 100, 23);

        dcsTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcsTanggalKeyPressed(evt);
            }
        });
        jPanel1.add(dcsTanggal);
        dcsTanggal.setBounds(365, 42, 142, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Pilih Tanggal :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(365, 22, 120, 15);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 82, 519, 315));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bek.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        MnuInput.setText("File");
        MnuInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mbExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mbExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mbExit.setMnemonic('x');
        mbExit.setText("Exit");
        mbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbExitActionPerformed(evt);
            }
        });
        MnuInput.add(mbExit);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setMnemonic('D');
        jMenuItem3.setText("Olah Data");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuInput.add(jMenuItem3);

        jMenuBar1.add(MnuInput);

        jMenu2.setMnemonic('H');
        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setMnemonic('e');
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setMnemonic('t');
        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mbExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DlgHelp help = new DlgHelp();
        help.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca"+"\n Lukman Kurniawan"+"\n NIM 1641801");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
try {
            String nama_kota = txtKota.getText();
            SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
            String tanggal = fmt.format(dcsTanggal.getDate());
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM t_cuaca WHERE nama_kota = '" + nama_kota +"' "
            + "AND date = '" + tanggal + "%' "
            + "LIMIT 1";
            ResultSet rs = st.executeQuery(query);
            

            while(rs.next()){
                //lblHari.setText(cbHari.getSelectedItem().toString());
                SimpleDateFormat fmt2 = new SimpleDateFormat("dd MMMM YYYY", Locale.forLanguageTag("Id"));
                lblHari.setText(fmt2.format(dcsTanggal.getDate()));
                lblMonitoring.setText("Cuaca di "+rs.getString("nama_kota"));
                lblMax.setText(rs.getString("suhu_maks")+" "+(char)0x00B0+" C");
                lblMin.setText(rs.getString("suhu_min")+" "+(char)0x00B0+" C");
                lblAngin.setText(rs.getString("kecepatan_angin")+" m/s");
                lblLembab.setText(rs.getString("kelembapan")+" %");
                lblTekanan.setText(rs.getString("tekanan_udara")+" hPa");
                lblSuhu.setText(rs.getString("suhu")+" "+(char)0x00B0+" C");
                String gambar = rs.getString("gambar");
                lblStatus.setText(rs.getString("status"));
                //String gambar2 = "C:\\Users\\USER\\Documents\\NetBeansProjects\\tugas4Visual\\src\\res\\"+gambar;
                //lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource(gambar2)));
                lblGambar.setIcon(new javax.swing.ImageIcon("C:/Users/USER/Documents/NetBeansProjects/tugas4Visual/src/res/"+gambar));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCuaca.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_txtKotaActionPerformed

    private void cmdTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTampilActionPerformed
      try {
            String nama_kota = txtKota.getText();
            SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
            String tanggal = fmt.format(dcsTanggal.getDate());
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM t_cuaca WHERE nama_kota = '" + nama_kota +"' "
            + "AND date = '" + tanggal + "%' "
            + "LIMIT 1";
            ResultSet rs = st.executeQuery(query);
            

            while(rs.next()){
                //lblHari.setText(cbHari.getSelectedItem().toString());
                SimpleDateFormat fmt2 = new SimpleDateFormat("dd MMMM YYYY", Locale.forLanguageTag("Id"));
                lblHari.setText(fmt2.format(dcsTanggal.getDate()));
                lblMonitoring.setText("Cuaca di "+rs.getString("nama_kota"));
                lblMax.setText(rs.getString("suhu_maks")+" "+(char)0x00B0+" C");
                lblMin.setText(rs.getString("suhu_min")+" "+(char)0x00B0+" C");
                lblAngin.setText(rs.getString("kecepatan_angin")+" m/s");
                lblLembab.setText(rs.getString("kelembapan")+" %");
                lblTekanan.setText(rs.getString("tekanan_udara")+" hPa");
                lblSuhu.setText(rs.getString("suhu")+" "+(char)0x00B0+" C");
                String gambar = rs.getString("gambar");
                lblStatus.setText(rs.getString("status"));
                //String gambar2 = "C:\\Users\\USER\\Documents\\NetBeansProjects\\tugas4Visual\\src\\res\\"+gambar;
                //lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource(gambar2)));
                lblGambar.setIcon(new javax.swing.ImageIcon("C:/Users/USER/Documents/NetBeansProjects/tugas4Visual/src/res/"+gambar));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCuaca.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_cmdTampilActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmLogin r = new frmLogin(con);
        r.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void dcsTanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcsTanggalKeyPressed
        // TODO add your handling code here:
        try {
            String nama_kota = txtKota.getText();
            SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
            String tanggal = fmt.format(dcsTanggal.getDate());
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM t_cuaca WHERE nama_kota = '" + nama_kota +"' "
            + "AND date = '" + tanggal + "%' "
            + "LIMIT 1";
            ResultSet rs = st.executeQuery(query);
            

            while(rs.next()){
                //lblHari.setText(cbHari.getSelectedItem().toString());
                SimpleDateFormat fmt2 = new SimpleDateFormat("dd MMMM YYYY", Locale.forLanguageTag("Id"));
                lblHari.setText(fmt2.format(dcsTanggal.getDate()));
                lblMonitoring.setText("Cuaca di "+rs.getString("nama_kota"));
                lblMax.setText(rs.getString("suhu_maks")+" "+(char)0x00B0+" C");
                lblMin.setText(rs.getString("suhu_min")+" "+(char)0x00B0+" C");
                lblAngin.setText(rs.getString("kecepatan_angin")+" m/s");
                lblLembab.setText(rs.getString("kelembapan")+" %");
                lblTekanan.setText(rs.getString("tekanan_udara")+" hPa");
                lblSuhu.setText(rs.getString("suhu")+" "+(char)0x00B0+" C");
                String gambar = rs.getString("gambar");
                lblStatus.setText(rs.getString("status"));
                //String gambar2 = "C:\\Users\\USER\\Documents\\NetBeansProjects\\tugas4Visual\\src\\res\\"+gambar;
                //lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource(gambar2)));
                lblGambar.setIcon(new javax.swing.ImageIcon("C:/Users/USER/Documents/NetBeansProjects/tugas4Visual/src/res/"+gambar));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmCuaca.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_dcsTanggalKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuInput;
    private javax.swing.JButton cmdTampil;
    private com.toedter.calendar.JDateChooser dcsTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblAngin;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblLembab;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMonitoring;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lblTekanan;
    private javax.swing.JMenuItem mbExit;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables

}
