/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.*;
import com.mysql.jdbc.Driver;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class frmDatabase extends javax.swing.JFrame {

    /**
     * Creates new form frmDatabase
     */
    public Connection con;
    
    public frmDatabase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaDatabase = new javax.swing.JTextField();
        txtNamaUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordUser = new javax.swing.JPasswordField();
        cmdKonek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Database");

        txtNamaDatabase.setName("txtNamaDatabase"); // NOI18N
        txtNamaDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDatabaseActionPerformed(evt);
            }
        });

        txtNamaUser.setName("txtNamaUser"); // NOI18N

        jLabel2.setText("Nama User");

        jLabel3.setText("Password User");

        txtPasswordUser.setName("txtPassword"); // NOI18N

        cmdKonek.setText("Koneksikan");
        cmdKonek.setName("cmdKonek"); // NOI18N
        cmdKonek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKonekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdKonek)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNamaDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtNamaUser)
                        .addComponent(txtPasswordUser)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdKonek)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDatabaseActionPerformed

    private void cmdKonekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKonekActionPerformed
        try {
            con = getConnection();
            
            System.out.println("ganteng");
            
            new FrmCuaca(con).setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Periksa kembali Nama Database, Nama User, dan Password User", "Koneksi ke database error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmdKonekActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdKonek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNamaDatabase;
    private javax.swing.JTextField txtNamaUser;
    private javax.swing.JPasswordField txtPasswordUser;
    // End of variables declaration//GEN-END:variables
public Connection getConnection() throws SQLException{
        if(con == null){
            String namaDatabase = txtNamaDatabase.getText();
            String namaUser = txtNamaUser.getText();
            String passwordUser = txtPasswordUser.getText();
            
            new Driver();
            con = DriverManager.getConnection("jdbc:mysql://localhost/" + namaDatabase, namaUser, passwordUser);
        }
        
        return con;
    }
}
