/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Cuaca;
/**
 *
 * @author USER
 */
public class frmOlahData extends javax.swing.JFrame {

    /**
     * Creates new form frmOlahData
     */
     Connection con;
    public frmOlahData(Connection con) {
        initComponents();
        tampil_tabel(con);
        this.con = con;
        
    }
public ArrayList<Cuaca> getCuacaList(Connection con){
    ArrayList<Cuaca> cuacaList = new ArrayList<Cuaca>();
    //Connection connection = getConnection();
    String query = "SELECT * FROM t_cuaca";
    Statement st;
    ResultSet rs;
    
    try{
        
        st = con.createStatement();
        rs = st.executeQuery(query);
        Cuaca cuaca;
        while(rs.next()){
            cuaca = new Cuaca(rs.getInt("ID"), rs.getDate("date"), rs.getString("nama_kota"), rs.getDouble("suhu"), rs.getDouble("suhu_maks"), rs.getDouble("suhu_min"), rs.getDouble("kecepatan_angin"), rs.getDouble("kelembapan"), rs.getDouble("tekanan_udara"),rs.getString("gambar"),rs.getString("status"));
            cuacaList.add(cuaca);
        }
    }catch(Exception e){
        e.printStackTrace();
    }
    return cuacaList;
}

public void tampil_tabel(Connection con){
    ArrayList<Cuaca> list = getCuacaList(con);
       DefaultTableModel model = (DefaultTableModel)tblCuaca.getModel();
       Object[] row = new Object[11];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getId();
           row[1] = list.get(i).getTanggal();
           row[2] = list.get(i).getNamaKota();
           row[3] = list.get(i).getSuhu();
           row[4] = list.get(i).getSuhuMaks();
           row[5] = list.get(i).getSuhuMin();
           row[6] = list.get(i).getKecepatanAngin();
           row[7] = list.get(i).getKelembapan();
           row[8] = list.get(i).getTekanan();
           row[9] = list.get(i).getGambar();
           row[10] = list.get(i).getStatus();
           model.addRow(row);
       }
}
 public void executeSQlQuery(String query, String message, Connection con)
   {
       
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)tblCuaca.getModel();
               model.setRowCount(0);
               tampil_tabel(con);
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtTekananUdara = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKecepatanAngin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtKelembapan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSuhuMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSuhuMaks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaKota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcsTanggal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuaca = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        cbBrowse = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 343, -1, -1));

        btnInput.setText("Insert");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 370, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        getContentPane().add(txtTekananUdara, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 102, -1));

        jLabel9.setText("Tekanan Udara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, -1, -1));
        getContentPane().add(txtKecepatanAngin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 102, -1));

        jLabel8.setText("Kecepatan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));
        getContentPane().add(txtKelembapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 102, -1));

        jLabel7.setText("Kelembapan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));
        getContentPane().add(txtSuhuMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 166, 102, -1));

        jLabel6.setText("Suhu Min");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));
        getContentPane().add(txtSuhuMaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 102, -1));

        jLabel5.setText("Suhu Maks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));
        getContentPane().add(txtSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 114, 102, -1));

        jLabel4.setText("Suhu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        txtNamaKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 84, 102, -1));

        jLabel3.setText("Nama Kota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));
        getContentPane().add(dcsTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 105, -1));

        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        tblCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Nama Kota", "Suhu", "Suhu Max", "Suhu Min", "Kecepatan Angin", "Kelembapan", "Tekanan Udara", "Gambar", "Status"
            }
        ));
        tblCuaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCuacaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCuaca);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 29, 722, 370));

        txtId.setEditable(false);
        txtId.setText(" ");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 34, -1));

        txtTgl.setEditable(false);
        txtTgl.setText(" ");
        getContentPane().add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 102, -1));

        cbBrowse.setText("Cari Gambar");
        cbBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(cbBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 343, -1, -1));
        getContentPane().add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 102, -1));
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 102, -1));

        jLabel1.setText("Status Cuaca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKotaActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
    SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");

            String tanggal = fmt.format(dcsTanggal.getDate());
            System.out.println(dcsTanggal.getDate());
            System.out.println(tanggal);
            String namaKota = txtNamaKota.getText();
            double suhu = Double.parseDouble(txtSuhu.getText());
            double suhuMaks = Double.parseDouble(txtSuhuMaks.getText());
            double suhuMin = Double.parseDouble(txtSuhuMin.getText());
            double kecepatanAngin = Double.parseDouble(txtKecepatanAngin.getText());
            double kelembapan = Double.parseDouble(txtKelembapan.getText());
            double tekananUdara = Double.parseDouble(txtTekananUdara.getText());
            String gambar = txtURL.getText();
            String status = txtStatus.getText();
        String query = "INSERT INTO t_cuaca ("
            + "date, "
            + "nama_kota, "
            + "suhu, "
            + "suhu_maks, "
            + "suhu_min, "
            + "kecepatan_angin, "
            + "kelembapan, "
            + "tekanan_udara, "
            + "gambar, "
            + "status) "
            + "VALUES "
            + "('" + tanggal + "', '" + namaKota + "', " + suhu + ", " + suhuMaks + ", " + suhuMin + ", " + kecepatanAngin + ", " + kelembapan + ", " + tekananUdara + ", '" + gambar + "', '" + status + "')";
        
        executeSQlQuery(query, "Inserted", con);        
    }//GEN-LAST:event_btnInputActionPerformed

    private void tblCuacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCuacaMouseClicked
        // TODO add your handling code here:
         int i = tblCuaca.getSelectedRow();

        TableModel model = tblCuaca.getModel();
       
        txtId.setText(model.getValueAt(i,0).toString());
        txtTgl.setText(model.getValueAt(i,1).toString());
        txtNamaKota.setText(model.getValueAt(i,2).toString());
        txtSuhu.setText(model.getValueAt(i,3).toString());
        txtSuhuMaks.setText(model.getValueAt(i,4).toString());
        txtSuhuMin.setText(model.getValueAt(i,5).toString());
        txtKecepatanAngin.setText(model.getValueAt(i,6).toString());
        txtKelembapan.setText(model.getValueAt(i,7).toString());
        txtTekananUdara.setText(model.getValueAt(i,8).toString());
        txtURL.setText(model.getValueAt(i, 9).toString());
        txtStatus.setText(model.getValueAt(i, 10).toString());
    }//GEN-LAST:event_tblCuacaMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");

            String tanggal = fmt.format(dcsTanggal.getDate());
            System.out.println(dcsTanggal.getDate());
            System.out.println(tanggal);
            String namaKota = txtNamaKota.getText();
            String gambar = txtURL.getText();
            String status = txtStatus.getText();
            double suhu = Double.parseDouble(txtSuhu.getText());
            double suhuMaks = Double.parseDouble(txtSuhuMaks.getText());
            double suhuMin = Double.parseDouble(txtSuhuMin.getText());
            double kecepatanAngin = Double.parseDouble(txtKecepatanAngin.getText());
            double kelembapan = Double.parseDouble(txtKelembapan.getText());
            double tekananUdara = Double.parseDouble(txtTekananUdara.getText());
            double id = Double.parseDouble((txtId.getText()));
        String query = "UPDATE `t_cuaca` SET `date` = '"+tanggal+"', " +
                        "`nama_kota` = '"+namaKota+"', `suhu` = '"+suhu+"', `suhu_maks` = '"+suhuMaks+"', " +
                        "`suhu_min` = '"+suhuMin+"', `kecepatan_angin` = '"+kecepatanAngin+"', `kelembapan` = '"+kelembapan+"', " +
                        "`tekanan_udara` = '"+tekananUdara+"', `gambar` = '"+gambar+"', `status` = '"+status+"'  WHERE `t_cuaca`.`ID` = '"+id+"'";
            
        
        executeSQlQuery(query, "Updated", con); 
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        double id = Double.parseDouble((txtId.getText()));
        String query = "DELETE FROM `t_cuaca` WHERE id = "+id;
         executeSQlQuery(query, "Deleted", con);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtTgl.setText("");
        txtNamaKota.setText("");
        txtSuhu.setText("");
        txtSuhuMaks.setText("");
        txtSuhuMin.setText("");
        txtKecepatanAngin.setText("");
        txtKelembapan.setText("");
        txtTekananUdara.setText("");
        txtURL.setText("");
        txtStatus.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:\\Users\\USER\\Documents\\NetBeansProjects\\tugas4Visual\\src\\res");
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        String dir = file.getName();
        txtURL.setText(dir);
    }//GEN-LAST:event_cbBrowseActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton cbBrowse;
    private com.toedter.calendar.JDateChooser dcsTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuaca;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKecepatanAngin;
    private javax.swing.JTextField txtKelembapan;
    private javax.swing.JTextField txtNamaKota;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSuhu;
    private javax.swing.JTextField txtSuhuMaks;
    private javax.swing.JTextField txtSuhuMin;
    private javax.swing.JTextField txtTekananUdara;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
